# name: Run main.py

# on:
#   schedule:
#     - cron: '0 11 * * *' # 每天 UTC 时间 11 点运行
#   workflow_dispatch: # 允许手动触发

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     timeout-minutes: 60 # 设置任务在 60 分钟后自动取消

#     steps:
#     - uses: actions/checkout@v2 # 获取仓库内容
#     - name: Set up Python 3.8
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.8
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#     - name: Run main.py
#       run: python main.py
