name: Run main.py

on:
  schedule:
    - cron: '0 10-16 * * *' # 每天的 10 点到 16 点，每小时的第 0 分钟运行

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 # 获取仓库内容

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run main.py
      run: python main.py
